import { defineConfig } from 'vitepress'
import { VitePWA } from 'vite-plugin-pwa'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: 'Owoer 知识库',
  description: '中医师承 | 程序员的英语 | 量化交易 — Used Dan 的技术知识库',
  base: '/owoer-tech/knowledge-base/',
  lang: 'zh-CN',
  lastUpdated: true,
  cleanUrls: true,

  /* ============================================
     PWA — vite-plugin-pwa (离线缓存)
     ============================================ */
  vite: {
    build: {
      target: 'es2020',
    },
    ssr: {
      noExternal: ['workbox-window'],
    },
    plugins: [
      VitePWA({
        registerType: 'autoUpdate',
        includeAssets: ['favicon.svg', 'logo.svg'],
        manifest: {
          name: 'Owoer 知识库',
          short_name: 'Owoer KB',
          description: '中医师承 | 程序员的英语 | 量化交易',
          theme_color: '#059669',
          background_color: '#ffffff',
          display: 'standalone',
          icons: [
            {
              src: '/owoer-tech/knowledge-base/favicon.svg',
              sizes: 'any',
              type: 'image/svg+xml',
              purpose: 'any maskable',
            },
          ],
        },
        workbox: {
          globPatterns: ['**/*.{js,css,html,svg,png,woff2}'],
          runtimeCaching: [
            {
              urlPattern: /^https:\/\/usedan\.github\.io\/owoer-tech\/knowledge-base\/.*/i,
              handler: 'StaleWhileRevalidate',
              options: {
                cacheName: 'vitepress-cache',
                expiration: {
                  maxEntries: 100,
                  maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
                },
              },
            },
          ],
        },
      }),
    ],
  },

  /* ============================================
     Head — 图标 & Umami & SEO
     ============================================ */
  head: [
    ['link', { rel: 'icon', href: '/owoer-tech/knowledge-base/favicon.svg' }],
    ['link', { rel: 'apple-touch-icon', href: '/owoer-tech/knowledge-base/favicon.svg' }],
    ['meta', { name: 'theme-color', content: '#059669' }],
    // Umami 分析（上线后取消注释，换成实际地址）
    // ['script', {
    //   defer: '',
    //   src: 'https://你的vps:端口/script.js',
    //   'data-website-id': '你的站点ID',
    // }],
  ],

  /* ============================================
     Theme — 导航 & 侧边栏
     ============================================ */
  themeConfig: {
    logo: { src: '/logo.svg', width: 110, height: 24 },

    nav: [
      { text: '首页', link: '/zh/' },
      {
        text: '中医师承',
        link: '/zh/book1-tcm/',
        activeMatch: '/zh/book1-tcm/',
      },
      {
        text: '程序员的英语',
        link: '/zh/book2-english/',
        activeMatch: '/zh/book2-english/',
      },
      {
        text: '量化交易',
        link: '/zh/book3-quant/',
        activeMatch: '/zh/book3-quant/',
      },
      {
        text: '渗透测试',
        link: '/zh/book4-pentest/',
        activeMatch: '/zh/book4-pentest/',
      },
      {
        text: 'SRC 学习',
        link: '/zh/book5-src-learning/',
        activeMatch: '/zh/book5-src-learning/',
      },
    ],

              sidebar: {
                '/zh/book1-tcm/': [
                  {
                    text: '中医师承出师考试',
                    link: '/zh/book1-tcm/',
                    items: [
                        {
                          text: "中医基础理论",
                          collapsed: true,
                          items: [
                            { text: '📖 科目概览', link: '/zh/book1-tcm/01-basic-theory/' },
                            {
                              text: '📋 考试大纲',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/01-basic-theory/syllabus-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/01-basic-theory/syllabus-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/01-basic-theory/syllabus-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/01-basic-theory/syllabus-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/01-basic-theory/syllabus-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/01-basic-theory/syllabus-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/01-basic-theory/syllabus-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/01-basic-theory/syllabus-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/01-basic-theory/syllabus-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/01-basic-theory/syllabus-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/01-basic-theory/syllabus-unit-11' },
                                { text: '单元12', link: '/zh/book1-tcm/01-basic-theory/syllabus-unit-12' },
                              ],
                            },
                            {
                              text: '📝 教材笔记',
                              collapsed: true,
                              items: [
                                { text: '单元3', link: '/zh/book1-tcm/01-basic-theory/notes-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/01-basic-theory/notes-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/01-basic-theory/notes-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/01-basic-theory/notes-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/01-basic-theory/notes-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/01-basic-theory/notes-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/01-basic-theory/notes-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/01-basic-theory/notes-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/01-basic-theory/notes-unit-11' },
                                { text: '单元12', link: '/zh/book1-tcm/01-basic-theory/notes-unit-12' },
                                { text: '单元13', link: '/zh/book1-tcm/01-basic-theory/notes-unit-13' },
                              ],
                            },
                          ],
                        },
                        {
                          text: "中医诊断学",
                          collapsed: true,
                          items: [
                            { text: '📖 科目概览', link: '/zh/book1-tcm/02-diagnostics/' },
                            {
                              text: '📋 考试大纲',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/02-diagnostics/syllabus-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/02-diagnostics/syllabus-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/02-diagnostics/syllabus-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/02-diagnostics/syllabus-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/02-diagnostics/syllabus-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/02-diagnostics/syllabus-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/02-diagnostics/syllabus-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/02-diagnostics/syllabus-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/02-diagnostics/syllabus-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/02-diagnostics/syllabus-unit-10' },
                              ],
                            },
                            {
                              text: '📝 教材笔记',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/02-diagnostics/notes-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/02-diagnostics/notes-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/02-diagnostics/notes-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/02-diagnostics/notes-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/02-diagnostics/notes-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/02-diagnostics/notes-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/02-diagnostics/notes-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/02-diagnostics/notes-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/02-diagnostics/notes-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/02-diagnostics/notes-unit-10' },
                              ],
                            },
                          ],
                        },
                        {
                          text: "中药学",
                          collapsed: true,
                          items: [
                            { text: '📖 科目概览', link: '/zh/book1-tcm/03-pharmacology/' },
                            {
                              text: '📋 考试大纲',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-11' },
                                { text: '单元14', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-14' },
                                { text: '单元15', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-15' },
                                { text: '单元16', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-16' },
                                { text: '单元17', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-17' },
                                { text: '单元18', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-18' },
                                { text: '单元19', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-19' },
                                { text: '单元20', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-20' },
                                { text: '单元21', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-21' },
                                { text: '单元22', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-22' },
                                { text: '单元23', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-23' },
                                { text: '单元99', link: '/zh/book1-tcm/03-pharmacology/syllabus-unit-99' },
                              ],
                            },
                            {
                              text: '📝 教材笔记',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/03-pharmacology/notes-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/03-pharmacology/notes-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/03-pharmacology/notes-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/03-pharmacology/notes-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/03-pharmacology/notes-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/03-pharmacology/notes-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/03-pharmacology/notes-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/03-pharmacology/notes-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/03-pharmacology/notes-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/03-pharmacology/notes-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/03-pharmacology/notes-unit-11' },
                                { text: '单元12', link: '/zh/book1-tcm/03-pharmacology/notes-unit-12' },
                                { text: '单元13', link: '/zh/book1-tcm/03-pharmacology/notes-unit-13' },
                                { text: '单元14', link: '/zh/book1-tcm/03-pharmacology/notes-unit-14' },
                                { text: '单元15', link: '/zh/book1-tcm/03-pharmacology/notes-unit-15' },
                                { text: '单元17', link: '/zh/book1-tcm/03-pharmacology/notes-unit-17' },
                                { text: '单元18', link: '/zh/book1-tcm/03-pharmacology/notes-unit-18' },
                                { text: '单元19', link: '/zh/book1-tcm/03-pharmacology/notes-unit-19' },
                                { text: '单元20', link: '/zh/book1-tcm/03-pharmacology/notes-unit-20' },
                                { text: '单元21', link: '/zh/book1-tcm/03-pharmacology/notes-unit-21' },
                                { text: '单元22', link: '/zh/book1-tcm/03-pharmacology/notes-unit-22' },
                                { text: '单元23', link: '/zh/book1-tcm/03-pharmacology/notes-unit-23' },
                                { text: '单元24', link: '/zh/book1-tcm/03-pharmacology/notes-unit-24' },
                              ],
                            },
                          ],
                        },
                        {
                          text: "方剂学",
                          collapsed: true,
                          items: [
                            { text: '📖 科目概览', link: '/zh/book1-tcm/04-prescriptions/' },
                            {
                              text: '📋 考试大纲',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-11' },
                                { text: '单元12', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-12' },
                                { text: '单元13', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-13' },
                                { text: '单元14', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-14' },
                                { text: '单元15', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-15' },
                                { text: '单元16', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-16' },
                                { text: '单元17', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-17' },
                                { text: '单元18', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-18' },
                                { text: '单元19', link: '/zh/book1-tcm/04-prescriptions/syllabus-unit-19' },
                              ],
                            },
                            {
                              text: '📝 教材笔记',
                              collapsed: true,
                              items: [
                                { text: '单元4', link: '/zh/book1-tcm/04-prescriptions/notes-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/04-prescriptions/notes-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/04-prescriptions/notes-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/04-prescriptions/notes-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/04-prescriptions/notes-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/04-prescriptions/notes-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/04-prescriptions/notes-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/04-prescriptions/notes-unit-11' },
                                { text: '单元12', link: '/zh/book1-tcm/04-prescriptions/notes-unit-12' },
                                { text: '单元13', link: '/zh/book1-tcm/04-prescriptions/notes-unit-13' },
                                { text: '单元14', link: '/zh/book1-tcm/04-prescriptions/notes-unit-14' },
                                { text: '单元15', link: '/zh/book1-tcm/04-prescriptions/notes-unit-15' },
                                { text: '单元16', link: '/zh/book1-tcm/04-prescriptions/notes-unit-16' },
                                { text: '单元17', link: '/zh/book1-tcm/04-prescriptions/notes-unit-17' },
                                { text: '单元18', link: '/zh/book1-tcm/04-prescriptions/notes-unit-18' },
                                { text: '单元19', link: '/zh/book1-tcm/04-prescriptions/notes-unit-19' },
                              ],
                            },
                          ],
                        },
                        {
                          text: "中医内科学",
                          collapsed: true,
                          items: [
                            { text: '📖 科目概览', link: '/zh/book1-tcm/05-internal-med/' },
                            {
                              text: '📋 考试大纲',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-11' },
                                { text: '单元12', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-12' },
                                { text: '单元13', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-13' },
                                { text: '单元14', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-14' },
                                { text: '单元15', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-15' },
                                { text: '单元16', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-16' },
                                { text: '单元17', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-17' },
                                { text: '单元18', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-18' },
                                { text: '单元19', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-19' },
                                { text: '单元20', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-20' },
                                { text: '单元21', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-21' },
                                { text: '单元22', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-22' },
                                { text: '单元23', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-23' },
                                { text: '单元24', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-24' },
                                { text: '单元25', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-25' },
                                { text: '单元26', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-26' },
                                { text: '单元27', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-27' },
                                { text: '单元28', link: '/zh/book1-tcm/05-internal-med/syllabus-unit-28' },
                              ],
                            },
                            {
                              text: '📝 教材笔记',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/05-internal-med/notes-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/05-internal-med/notes-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/05-internal-med/notes-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/05-internal-med/notes-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/05-internal-med/notes-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/05-internal-med/notes-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/05-internal-med/notes-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/05-internal-med/notes-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/05-internal-med/notes-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/05-internal-med/notes-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/05-internal-med/notes-unit-11' },
                                { text: '单元12', link: '/zh/book1-tcm/05-internal-med/notes-unit-12' },
                                { text: '单元13', link: '/zh/book1-tcm/05-internal-med/notes-unit-13' },
                                { text: '单元14', link: '/zh/book1-tcm/05-internal-med/notes-unit-14' },
                                { text: '单元15', link: '/zh/book1-tcm/05-internal-med/notes-unit-15' },
                                { text: '单元16', link: '/zh/book1-tcm/05-internal-med/notes-unit-16' },
                                { text: '单元17', link: '/zh/book1-tcm/05-internal-med/notes-unit-17' },
                                { text: '单元18', link: '/zh/book1-tcm/05-internal-med/notes-unit-18' },
                                { text: '单元19', link: '/zh/book1-tcm/05-internal-med/notes-unit-19' },
                                { text: '单元20', link: '/zh/book1-tcm/05-internal-med/notes-unit-20' },
                                { text: '单元21', link: '/zh/book1-tcm/05-internal-med/notes-unit-21' },
                                { text: '单元22', link: '/zh/book1-tcm/05-internal-med/notes-unit-22' },
                                { text: '单元23', link: '/zh/book1-tcm/05-internal-med/notes-unit-23' },
                                { text: '单元24', link: '/zh/book1-tcm/05-internal-med/notes-unit-24' },
                                { text: '单元25', link: '/zh/book1-tcm/05-internal-med/notes-unit-25' },
                                { text: '单元26', link: '/zh/book1-tcm/05-internal-med/notes-unit-26' },
                                { text: '单元27', link: '/zh/book1-tcm/05-internal-med/notes-unit-27' },
                                { text: '单元28', link: '/zh/book1-tcm/05-internal-med/notes-unit-28' },
                              ],
                            },
                          ],
                        },
                        {
                          text: "中医外科学",
                          collapsed: true,
                          items: [
                            { text: '📖 科目概览', link: '/zh/book1-tcm/06-surgery/' },
                            {
                              text: '📋 考试大纲',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/06-surgery/syllabus-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/06-surgery/syllabus-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/06-surgery/syllabus-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/06-surgery/syllabus-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/06-surgery/syllabus-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/06-surgery/syllabus-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/06-surgery/syllabus-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/06-surgery/syllabus-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/06-surgery/syllabus-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/06-surgery/syllabus-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/06-surgery/syllabus-unit-11' },
                                { text: '单元12', link: '/zh/book1-tcm/06-surgery/syllabus-unit-12' },
                                { text: '单元13', link: '/zh/book1-tcm/06-surgery/syllabus-unit-13' },
                              ],
                            },
                            {
                              text: '📝 教材笔记',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/06-surgery/notes-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/06-surgery/notes-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/06-surgery/notes-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/06-surgery/notes-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/06-surgery/notes-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/06-surgery/notes-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/06-surgery/notes-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/06-surgery/notes-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/06-surgery/notes-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/06-surgery/notes-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/06-surgery/notes-unit-11' },
                                { text: '单元12', link: '/zh/book1-tcm/06-surgery/notes-unit-12' },
                                { text: '单元13', link: '/zh/book1-tcm/06-surgery/notes-unit-13' },
                              ],
                            },
                          ],
                        },
                        {
                          text: "中医妇科学",
                          collapsed: true,
                          items: [
                            { text: '📖 科目概览', link: '/zh/book1-tcm/07-gynecology/' },
                            {
                              text: '📋 考试大纲',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/07-gynecology/syllabus-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/07-gynecology/syllabus-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/07-gynecology/syllabus-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/07-gynecology/syllabus-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/07-gynecology/syllabus-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/07-gynecology/syllabus-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/07-gynecology/syllabus-unit-07' },
                              ],
                            },
                            {
                              text: '📝 教材笔记',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/07-gynecology/notes-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/07-gynecology/notes-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/07-gynecology/notes-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/07-gynecology/notes-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/07-gynecology/notes-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/07-gynecology/notes-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/07-gynecology/notes-unit-07' },
                              ],
                            },
                          ],
                        },
                        {
                          text: "中医儿科学",
                          collapsed: true,
                          items: [
                            { text: '📖 科目概览', link: '/zh/book1-tcm/08-pediatrics/' },
                            {
                              text: '📋 考试大纲',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-11' },
                                { text: '单元12', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-12' },
                                { text: '单元13', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-13' },
                                { text: '单元14', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-14' },
                                { text: '单元15', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-15' },
                                { text: '单元16', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-16' },
                                { text: '单元17', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-17' },
                                { text: '单元18', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-18' },
                                { text: '单元19', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-19' },
                                { text: '单元20', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-20' },
                                { text: '单元21', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-21' },
                                { text: '单元22', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-22' },
                                { text: '单元23', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-23' },
                                { text: '单元24', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-24' },
                                { text: '单元25', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-25' },
                                { text: '单元26', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-26' },
                                { text: '单元27', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-27' },
                                { text: '单元28', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-28' },
                                { text: '单元29', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-29' },
                                { text: '单元30', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-30' },
                                { text: '单元31', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-31' },
                                { text: '单元32', link: '/zh/book1-tcm/08-pediatrics/syllabus-unit-32' },
                              ],
                            },
                            {
                              text: '📝 教材笔记',
                              collapsed: true,
                              items: [
                                { text: '单元3', link: '/zh/book1-tcm/08-pediatrics/notes-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/08-pediatrics/notes-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/08-pediatrics/notes-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/08-pediatrics/notes-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/08-pediatrics/notes-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/08-pediatrics/notes-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/08-pediatrics/notes-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/08-pediatrics/notes-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/08-pediatrics/notes-unit-11' },
                                { text: '单元12', link: '/zh/book1-tcm/08-pediatrics/notes-unit-12' },
                                { text: '单元13', link: '/zh/book1-tcm/08-pediatrics/notes-unit-13' },
                                { text: '单元14', link: '/zh/book1-tcm/08-pediatrics/notes-unit-14' },
                                { text: '单元15', link: '/zh/book1-tcm/08-pediatrics/notes-unit-15' },
                                { text: '单元16', link: '/zh/book1-tcm/08-pediatrics/notes-unit-16' },
                                { text: '单元17', link: '/zh/book1-tcm/08-pediatrics/notes-unit-17' },
                                { text: '单元18', link: '/zh/book1-tcm/08-pediatrics/notes-unit-18' },
                                { text: '单元19', link: '/zh/book1-tcm/08-pediatrics/notes-unit-19' },
                                { text: '单元20', link: '/zh/book1-tcm/08-pediatrics/notes-unit-20' },
                                { text: '单元21', link: '/zh/book1-tcm/08-pediatrics/notes-unit-21' },
                                { text: '单元22', link: '/zh/book1-tcm/08-pediatrics/notes-unit-22' },
                                { text: '单元23', link: '/zh/book1-tcm/08-pediatrics/notes-unit-23' },
                                { text: '单元24', link: '/zh/book1-tcm/08-pediatrics/notes-unit-24' },
                                { text: '单元25', link: '/zh/book1-tcm/08-pediatrics/notes-unit-25' },
                                { text: '单元26', link: '/zh/book1-tcm/08-pediatrics/notes-unit-26' },
                                { text: '单元27', link: '/zh/book1-tcm/08-pediatrics/notes-unit-27' },
                                { text: '单元28', link: '/zh/book1-tcm/08-pediatrics/notes-unit-28' },
                                { text: '单元29', link: '/zh/book1-tcm/08-pediatrics/notes-unit-29' },
                                { text: '单元30', link: '/zh/book1-tcm/08-pediatrics/notes-unit-30' },
                                { text: '单元31', link: '/zh/book1-tcm/08-pediatrics/notes-unit-31' },
                                { text: '单元32', link: '/zh/book1-tcm/08-pediatrics/notes-unit-32' },
                              ],
                            },
                          ],
                        },
                        {
                          text: "针灸学",
                          collapsed: true,
                          items: [
                            { text: '📖 科目概览', link: '/zh/book1-tcm/09-acupuncture/' },
                            {
                              text: '📋 考试大纲',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-11' },
                                { text: '单元12', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-12' },
                                { text: '单元13', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-13' },
                                { text: '单元14', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-14' },
                                { text: '单元15', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-15' },
                                { text: '单元16', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-16' },
                                { text: '单元17', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-17' },
                                { text: '单元18', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-18' },
                                { text: '单元19', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-19' },
                                { text: '单元20', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-20' },
                                { text: '单元21', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-21' },
                                { text: '单元22', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-22' },
                                { text: '单元23', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-23' },
                                { text: '单元24', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-24' },
                                { text: '单元25', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-25' },
                                { text: '单元26', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-26' },
                                { text: '单元27', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-27' },
                                { text: '单元28', link: '/zh/book1-tcm/09-acupuncture/syllabus-unit-28' },
                              ],
                            },
                            {
                              text: '📝 教材笔记',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/09-acupuncture/notes-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/09-acupuncture/notes-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/09-acupuncture/notes-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/09-acupuncture/notes-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/09-acupuncture/notes-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/09-acupuncture/notes-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/09-acupuncture/notes-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/09-acupuncture/notes-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/09-acupuncture/notes-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/09-acupuncture/notes-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/09-acupuncture/notes-unit-11' },
                                { text: '单元12', link: '/zh/book1-tcm/09-acupuncture/notes-unit-12' },
                                { text: '单元13', link: '/zh/book1-tcm/09-acupuncture/notes-unit-13' },
                                { text: '单元14', link: '/zh/book1-tcm/09-acupuncture/notes-unit-14' },
                                { text: '单元15', link: '/zh/book1-tcm/09-acupuncture/notes-unit-15' },
                                { text: '单元16', link: '/zh/book1-tcm/09-acupuncture/notes-unit-16' },
                                { text: '单元17', link: '/zh/book1-tcm/09-acupuncture/notes-unit-17' },
                                { text: '单元18', link: '/zh/book1-tcm/09-acupuncture/notes-unit-18' },
                                { text: '单元19', link: '/zh/book1-tcm/09-acupuncture/notes-unit-19' },
                                { text: '单元20', link: '/zh/book1-tcm/09-acupuncture/notes-unit-20' },
                                { text: '单元21', link: '/zh/book1-tcm/09-acupuncture/notes-unit-21' },
                                { text: '单元22', link: '/zh/book1-tcm/09-acupuncture/notes-unit-22' },
                                { text: '单元23', link: '/zh/book1-tcm/09-acupuncture/notes-unit-23' },
                                { text: '单元24', link: '/zh/book1-tcm/09-acupuncture/notes-unit-24' },
                                { text: '单元25', link: '/zh/book1-tcm/09-acupuncture/notes-unit-25' },
                                { text: '单元26', link: '/zh/book1-tcm/09-acupuncture/notes-unit-26' },
                                { text: '单元27', link: '/zh/book1-tcm/09-acupuncture/notes-unit-27' },
                                { text: '单元28', link: '/zh/book1-tcm/09-acupuncture/notes-unit-28' },
                                { text: '单元29', link: '/zh/book1-tcm/09-acupuncture/notes-unit-29' },
                                { text: '单元30', link: '/zh/book1-tcm/09-acupuncture/notes-unit-30' },
                                { text: '单元31', link: '/zh/book1-tcm/09-acupuncture/notes-unit-31' },
                                { text: '单元32', link: '/zh/book1-tcm/09-acupuncture/notes-unit-32' },
                              ],
                            },
                          ],
                        },
                        {
                          text: "实践技能",
                          collapsed: true,
                          items: [
                            { text: '📖 科目概览', link: '/zh/book1-tcm/10-practice/' },
                            { text: '📋 考试大纲', link: '/zh/book1-tcm/10-practice/syllabus' },
                            {
                              text: '📝 教材笔记',
                              collapsed: true,
                              items: [
                                { text: '单元1', link: '/zh/book1-tcm/10-practice/notes-unit-01' },
                                { text: '单元2', link: '/zh/book1-tcm/10-practice/notes-unit-02' },
                                { text: '单元3', link: '/zh/book1-tcm/10-practice/notes-unit-03' },
                                { text: '单元4', link: '/zh/book1-tcm/10-practice/notes-unit-04' },
                                { text: '单元5', link: '/zh/book1-tcm/10-practice/notes-unit-05' },
                                { text: '单元6', link: '/zh/book1-tcm/10-practice/notes-unit-06' },
                                { text: '单元7', link: '/zh/book1-tcm/10-practice/notes-unit-07' },
                                { text: '单元8', link: '/zh/book1-tcm/10-practice/notes-unit-08' },
                                { text: '单元9', link: '/zh/book1-tcm/10-practice/notes-unit-09' },
                                { text: '单元10', link: '/zh/book1-tcm/10-practice/notes-unit-10' },
                                { text: '单元11', link: '/zh/book1-tcm/10-practice/notes-unit-11' },
                                { text: '单元12', link: '/zh/book1-tcm/10-practice/notes-unit-12' },
                                { text: '单元13', link: '/zh/book1-tcm/10-practice/notes-unit-13' },
                                { text: '单元14', link: '/zh/book1-tcm/10-practice/notes-unit-14' },
                                { text: '单元15', link: '/zh/book1-tcm/10-practice/notes-unit-15' },
                                { text: '单元16', link: '/zh/book1-tcm/10-practice/notes-unit-16' },
                                { text: '单元17', link: '/zh/book1-tcm/10-practice/notes-unit-17' },
                                { text: '单元18', link: '/zh/book1-tcm/10-practice/notes-unit-18' },
                                { text: '单元19', link: '/zh/book1-tcm/10-practice/notes-unit-19' },
                                { text: '单元20', link: '/zh/book1-tcm/10-practice/notes-unit-20' },
                                { text: '单元21', link: '/zh/book1-tcm/10-practice/notes-unit-21' },
                                { text: '单元22', link: '/zh/book1-tcm/10-practice/notes-unit-22' },
                                { text: '单元23', link: '/zh/book1-tcm/10-practice/notes-unit-23' },
                                { text: '单元24', link: '/zh/book1-tcm/10-practice/notes-unit-24' },
                                { text: '单元25', link: '/zh/book1-tcm/10-practice/notes-unit-25' },
                                { text: '单元26', link: '/zh/book1-tcm/10-practice/notes-unit-26' },
                                { text: '单元27', link: '/zh/book1-tcm/10-practice/notes-unit-27' },
                                { text: '单元28', link: '/zh/book1-tcm/10-practice/notes-unit-28' },
                                { text: '单元29', link: '/zh/book1-tcm/10-practice/notes-unit-29' },
                                { text: '单元30', link: '/zh/book1-tcm/10-practice/notes-unit-30' },
                                { text: '单元31', link: '/zh/book1-tcm/10-practice/notes-unit-31' },
                                { text: '单元32', link: '/zh/book1-tcm/10-practice/notes-unit-32' },
                              ],
                            },
                          ],
                        }
                    ],
                  },
                ],
                '/zh/book3-quant/': [
                  {
                    text: '量化交易',
                    link: '/zh/book3-quant/',
                    items: [
                      { text: '📖 概览', link: '/zh/book3-quant/' },
                      { text: '🔗 Ptrade 外部互联方案', link: '/zh/book3-quant/ptrade-guide' },
                      { text: '📈 PE/PEG 股票估值入门', link: '/zh/book3-quant/pe-peg-valuation' },
                    ],
                  },
                ],
                '/zh/book4-pentest/': [
                  {
                    text: '渗透测试',
                    link: '/zh/book4-pentest/',
                    items: [
                      { text: '📖 概览', link: '/zh/book4-pentest/' },
                      {
                        text: '🔧 路由器渗透测试',
                        collapsed: true,
                        items: [
                          { text: 'Kali Linux 路由器渗透测试指南', link: '/zh/book4-pentest/kali-router-guide' },
                          { text: '华为 CPE 渗透测试步骤', link: '/zh/book4-pentest/huawei-cpe-pentest' },
                          { text: '渗透测试常用工具速查', link: '/zh/book4-pentest/tools-cheatsheet' },
                        ],
                      },
                      {
                        text: '🤖 Web 自动化',
                        collapsed: true,
                        items: [
                          { text: '反检测浏览器实践指南', link: '/zh/book4-pentest/anti-detection-browser' },
                          { text: '在线教育平台渗透笔记', link: '/zh/book4-pentest/education-platform-pentest' },
                        ],
                      },
                    ],
                  },
                ],
              },
              '/zh/book5-src-learning/': [
                {
                  text: 'SRC 漏洞挖掘',
                  link: '/zh/book5-src-learning/',
                  items: [
                    { text: '📖 概览', link: '/zh/book5-src-learning/' },
                    { text: '📝 PortSwigger Day1 笔记', link: '/zh/book5-src-learning/notes-day1' },
                  ],
                },
              ],

    socialLinks: [
      { icon: 'github', link: 'https://github.com/UsedDan' },
      {
        icon: {
          svg: '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M17.813 4.653h.854c1.51.054 2.769.578 3.773 1.574 1.004.995 1.524 2.249 1.56 3.76v7.36c-.036 1.51-.556 2.769-1.56 3.773s-2.262 1.524-3.773 1.56H5.333c-1.51-.036-2.769-.556-3.773-1.56S.036 18.858 0 17.347v-7.36c.036-1.511.556-2.765 1.56-3.76 1.004-.996 2.262-1.52 3.773-1.574h.774l-1.174-1.12a1.234 1.234 0 0 1-.373-.906c0-.356.124-.658.373-.907l.027-.027c.267-.249.573-.373.92-.373.347 0 .662.124.947.373L9.253 4.68c.142.124.249.258.32.4.071.142.107.284.107.426 0 .142-.036.275-.107.4-.071.124-.178.258-.32.4l-.027.027c-.142.124-.284.222-.426.293a1.03 1.03 0 0 1-.427.107c-.16 0-.311-.036-.453-.107a1.264 1.264 0 0 1-.4-.293l-.32-.32h-.746c-.373.035-.707.133-1 .293-.293.16-.542.382-.746.667-.204.284-.338.6-.4.946-.062.347-.08.698-.053 1.054h12.853c.018-.356 0-.707-.053-1.054-.054-.347-.187-.662-.4-.946-.213-.285-.462-.507-.747-.667-.284-.16-.618-.258-1-.293H15.04c-.124.107-.249.187-.373.24-.125.053-.267.08-.427.08-.16 0-.311-.027-.453-.08a1.388 1.388 0 0 1-.4-.24c-.124-.107-.222-.231-.293-.374a.963.963 0 0 1-.107-.426c0-.151.036-.293.107-.427.07-.133.169-.258.293-.373l.027-.027c.124-.142.258-.249.4-.32a1.11 1.11 0 0 1 .427-.107c.16 0 .302.036.426.107.125.071.259.178.4.32l1.227 1.12zM7.234 15.154c.408 0 .756-.14 1.043-.422.288-.281.43-.631.43-1.049 0-.418-.142-.768-.43-1.049-.287-.281-.635-.422-1.043-.422s-.756.14-1.043.422c-.287.281-.43.631-.43 1.049 0 .418.143.768.43 1.049.287.281.635.422 1.043.422zm9.532 0c.408 0 .756-.14 1.043-.422.288-.281.43-.631.43-1.049 0-.418-.142-.768-.43-1.049-.287-.281-.635-.422-1.043-.422s-.756.14-1.043.422c-.287.281-.43.631-.43 1.049 0 .418.143.768.43 1.049.287.281.635.422 1.043.422z" fill="currentColor"/></svg>',
        },
        link: 'https://space.bilibili.com/502947858',
      },
    ],

    footer: {
      message: 'Owoer Knowledge Base · Used Dan',
      copyright: 'MIT Licensed',
    },

    search: {
      provider: 'local',
    },

    // 上一篇/下一篇
    docFooter: {
      prev: '上一篇',
      next: '下一篇',
    },

    // 外观
    appearance: 'true', // 跟随系统
  },
})
